### PR TITLE
Create PawnKinds_StarVampire.xml

### PR DESCRIPTION
**Pull request by lex1975**

### CODE REVIEW

**Comment by lex1975** [comment]
I translated all the modifications into Russian. Please add this to your code.

**Comment by erdelf** [comment]
For the love of Christ stop.
None of these are getting accepted.

Make one pull request for the entire translation.

**Comment by lex1975** [comment]
how to do it?
Excuse me, I have some experience in translating mods of maincraft. There are few language files.

**Comment by erdelf** [comment]
You can include multiple files in a pull request.

**Comment by lex1975** [comment]
I try. I receive the message "Uploads are disabled. File uploads require push access to this repository."

**Comment by erdelf** [comment]
all your changes, pack them in one branch and then do the pull request from there.

**Pull request closed without merging**
